# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none


pool:
  vmImage: ubuntu-latest

steps:

- task: CmdLine@2
  inputs:
    script: 'ls -l /home/vsts/work/1/s'

- task: CmdLine@2
  inputs:
    script: |
      cd /home/vsts/work/1/s
      tree
- task: S3Upload@1
  inputs:
    awsCredentials: 'AWS'
    regionName: 'us-east-1'
    bucketName: 'proyecto-ort-2022g2-argocd'
    sourceFolder: '/home/vsts/work/1/s'
    globExpressions: '**.yml'
    targetFolder: 'orders'